__init__.py
from flask import Flask, request, current_app, g, session
from flask_babel import Babel, refresh
from flask_login import LoginManager
from cssa.config import DevConfig
from cssa.authentication.forms import is_hidden_field

# need to read flask-security to add in more secure methods
# need to look up cookie setting in flask-login for security consideration 
# need to set up https credentials

babel = Babel()
login_manager = LoginManager()

def create_app(config_class=DevConfig):
    
    app = Flask(__name__)
    babel.init_app(app)
    login_manager.init_app(app)
    app.config.from_object(config_class)

    from cssa.main import bp as main
    app.register_blueprint(main)

    from cssa.authentication import bp as auth
    app.register_blueprint(auth, url_prefix='/auth')
    
    from cssa.service import bp as service
    app.register_blueprint(service, url_prefix="/service")

    # set jinja2 external function
    app.jinja_env.globals['bootstrap_is_hidden_field'] = is_hidden_field

    return app

@babel.localeselector
def get_locale():
    if 'language' in session:
        return session['language']
    return request.accept_languages.best_match(current_app.config['LANGUAGES'], default='en')

main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from cssa.main import routes

main/routes.py
import os

from flask import render_template, request, current_app, url_for, flash, g, redirect, session
from flask_babel import _, get_locale, refresh, lazy_gettext as _l
from cssa.main import bp
from cssa.text import homeIntro

@bp.route('/')
@bp.route('/index')
def index():
    slides = []
    for fileA in os.listdir(current_app.config['HOME_CAROUSEL_FOLDER_LINK']):
        if fileA.endswith('.jpg'):
            slides.append((fileA.replace('.jpg', ''), 
                           url_for('static', filename='images/home/carousel/'+fileA)))
    
    return render_template('index.html', slides=slides, youtube=current_app.config['YOUTUBE'], info=homeIntro, title=_l("Home"))


@bp.route('/changelang', methods=['POST'])
def changelang():
    lang = request.form['changelang']
    if lang and lang in current_app.config['LANGUAGES']:
        session['language'] = lang
    return ("", 200)


@bp.before_request
def before_request():
    g.locale = str(get_locale())

service/__init__.py
from flask import Blueprint

bp = Blueprint('service', __name__)

from cssa.service import routes, infoRequest

service/routes.py
from hashlib import md5
from flask import redirect, render_template, current_app, request
from flask_login import login_required
from cssa.service import bp
from cssa.service.infoRequest import get_location

@bp.route("/index")
def index():
    link = "https://www.gravatar.com/avatar/{}?d=identicon&s={}".format(md5("123456".encode('utf-8')).hexdigest(), 36)
    
    locationInfo = get_location(request.remote_addr)
    if locationInfo[0] != 'Error':
        

    return render_template('service/index.html', link=link)

templates/base.html
{% extends "bootstrap_base.html" %}

{% block title %}
    {% if title %}CSSA|{{ title }}{% else %}CSSA{% endif %}
{% endblock %}

{% block metas%}
    {{ super() }}
    <meta charset='utf-8'>
    <meta name="author" content="Siheng Pan">
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">
            <img src="{{ url_for('static', filename='images/icon.png') }}" width="30" height="30" class="d-inline-block align-top" alt="Logo">
            UIUC CSSA
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item" >
                    <a class="nav-link" href="#">{{ _('Home') }}<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">{{ _('About') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">{{ _('Division') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">{{ _('Events') }}</a>
                </li>
                <li class="nav-item" style="white-space: nowrap;">
                    <a class="nav-link" href="#">{{ _('Sponsors and Partners') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('service.index') }}">{{ _('Service') }}</a>
                </li>
            </ul>
            <form class="form-inline">
                {% if g.locale and g.locale == 'zh' %}
                    <button id="changeLang" class="btn btn-outline-primary mr-3" type="button" data-lang="en">English</button>
                {% else %}
                    <button id="changeLang" class="btn btn-outline-primary mr-3" type="button" data-lang="zh">中文</button>
                {% endif %}
                <a href="{{ url_for('auth.sign_in_up') }}"><button class="btn btn-outline-primary" type="button">{{ _('Login') }}</button></a>
            </form>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container-fluid px-0">
        {% with messages = get_flashed_messages() %}
            {% for message in messages%}
                <div class="alert alert-info mb-0" role="alert">{{ message }}</div>
            {% endfor%}
        {%endwith%}
    {% block app_content %}{% endblock %}
    </div>
    
{% endblock %}

{% block models%}
{% endblock %}

{% block footer %}
    <div class="container-fluid bg-dark">
        <footer class="pt-4 pb-3 border-top">
            <div class="row align-items-center">
                <div class="col-12 col-md">
                    <img class="mb-2" src="{{ url_for('static', filename='images/icon.png') }}" alt width="50" height="50">
                    <small class='d-block text-muted'>Supported by UIUC CSSA IT 2019-2020</small> 
                </div>
                <div class="col-12 col-md">
                    <button type="button" class="btn btn-danger d-inline-block mb-2 w-100">Subsribe To Newsletter</button>
                    <div class="d-flex flex-row align-items-center justify-content-center">
                        <div class="mr-3"><a href="https://www.facebook.com/cssa.uiuc/"><img src="{{ url_for('static', filename='images/facebook.png') }}"></a></div>
                        <div class="mr-3"><a href="http://weibo.com/u/3172392617"><img src="{{ url_for('static', filename='images/weibo.png') }}"></a></div>
                        <div class="mr-3"><a href="https://www.youtube.com/channel/UCkZJjpHQ0lV4zIshqIgO89Q"><img src="{{ url_for('static', filename='images/youtube.png') }}"></a></div>
                        <div class="mr-3"><a href="http://uiuccssa.org/2018/mailto:uiuccssa.contact@gmail.com"><img src="{{ url_for('static', filename='images/email.png') }}"></a></div>
                    </div>
                </div>
                <div class="col-12 col-md">
                    <img id="qr" class="d-block mx-auto" src="{{ url_for('static', filename='images/qr.jpg') }}">
                </div>
            </div>
        </footer>
    </div>

{% endblock %}



{% block scripts %}
    {{ super() }}

    <script>
        $("#changeLang").click(function() {
            $.post('/changelang', {
                changelang: $('#changeLang').attr('data-lang')
            }).done(function() {
                location.reload(true);
            }).fail(function() {
                console.log("{{ _('Error: Could not contact server') }}");
            });
        })
    </script>
{% endblock %}

templates/bootstrap_base.html
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{title|default}}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link href="{{ url_for('static', filename='css/lib/bootstrap.min.css') }}" rel="stylesheet">
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {% endblock navbar %}
    {% block content -%}
    {%- endblock content %}

    {% block footer%}
    {%- endblock %}

    {% block modals %}
    {%- endblock %}

    {% block scripts %}
    <script src="{{ url_for('static', filename='js/lib/jquery-3.3.1.min.js') }}" ></script>
    <script src="{{ url_for('static', filename='js/lib/popper.min.js') }}"></script>
    {# it seems like /static/bootstrap/js/... can trigger old bootstrap file to load #}
    <script src="{{ url_for('static', filename='js/lib/bootstrap.min.js') }}" ></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>

templates/index.html
{% extends "base.html" %}

{% block app_content %}

    {% if slides and slides|length > 0 %}
    <div class="container-fluid px-0" id="homeCarouselContainer">
        <div id="homeCarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                {# first one has to be always active #} 
                <div class="carousel-item active">
                    <img class = "d-block w-100" src="{{ slides[0][1] }}", alt="{{ slides[0][0] }}">
                </div>
                {% for i in range(1, slides|length) %}
                    <div class="carousel-item">
                            <img class = "d-block w-100" src="{{ slides[i][1] }}", alt="{{ slides[i][0] }}">
                    </div>
                {% endfor %}
            </div>
        </div>

        {% if slides|length > 1 %}
            <a class="carousel-control-prev" href="#homeCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#homeCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        {% endif %}
    </div>
    {% endif %}
    {% if youtube and info %} 
        <div class="container bg-white mb-3" id="homeIntro">
            <div class="row">
                <div class="col-md-6 col-grid-divider">
                    {% for line in info %}
                        <p class="text-justify">{{ line }}</p>
                    {% endfor %}
                </div>
                <div class="col-md-6">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="{{ youtube }}" allowfullscreen width="50%" height="50%"></iframe>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/service/base.html
{% extends "service/semantic_base.html" %}

{% block title %}
    {% if title %}Service|{{ title }}{% else %}Service{% endif %}
{% endblock %}

{% block metas %}
    {{ super() }}
    <meta charset='utf-8'>
    <meta name="author" content="Siheng Pan">
{% endblock %}

{% block styles %}
{{ super() }}
<link href="{{ url_for('static', filename='css/service_index.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="ui top attached menu">
        <a class="item">
            <i class="sidebar icon"></i>
            Menu
        </a>
    </div>
    <div class="ui bottom attached segment pushable">
        <div id="menu" class="ui inverted left vertical sidebar menu">
            <div class="item">
                <a href="javascript:void(0)" class="ui mini circular logo icon image">
                    <img src="{{ link }}">
                </a>
                <b>
                    Hello, Anonymous!
                </b>
            </div>
            <a class="item active" href="{{ url_for('service.index') }}">
                Home
            </a>
        </div>
        <div class="pusher blurring">
            <div class="ui basic segment">
                {% block app_content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $('.ui.sidebar').sidebar({
            context: $('.bottom.segment')
        }).sidebar('attach events', '.menu .item')
    </script>
{% endblock %}

templates/service/index.html
{% extends "service/base.html" %}

{% block app_content %}
    <h3 class="ui header">
        <i class="bullhorn icon"></i>
        Dashboard
    </h3>
    <div class="ui grid">
        <div class="four wide column">
            
        </div>
        <div class="ten wide column">
            <div class="ui horizontal statistic">
                <div class="value">
                    2204
                </div>
                <div class="label">
                    views
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/service/semantic_base.html
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{title|default}}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Semantic -->
    <link href="{{ url_for('static', filename='libs/semantic/semantic.min.css') }}" rel="stylesheet">
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block content -%}
    {%- endblock content %}

    {% block footer%}
    {%- endblock %}

    {% block modals %}
    {%- endblock %}

    {% block scripts %}
    <script src="{{ url_for('static', filename='js/lib/jquery-3.3.1.min.js') }}" ></script>
    <script src="{{ url_for('static', filename='libs/semantic/semantic.min.js') }}" ></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>

templates/wtf.html
{% macro from_errors(form, hiddens=True) %}
    {%- if form.errors %}
        {%- for fieldname, errors in form.errors %}
            {%- if bootstrap_is_hidden_field(form[fieldname]) and hiddens or 
                not bootstrap_is_hidden_field(form[fieldname]) and hiddens != 'only' %}
                {%- for error in errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {%- endfor%}
            {%- endif %}
        {%- endfor %}
    {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False, required=False) %}
    {% if form_type == "horizontal "%}
        {% if add_group %}
            <div class="form-group row">
        {% endif %}
                <div class="col-{{ horizontal_columns[0] }}-{{ horizontal_columns[1] }} 
                            offset-{{ horizontal_columns[0] }}-{{ horizontal_columns[2] }}">        
                </div>
    {% endif %}
    {{ caller() }}

    {% if form_type == "horizontal" %}
        {% if add_group%}
            </div>
        {% endif %}
    {% endif %}
{% endmacro %}

{% macro form_field(field, 
                    form_type="basic",
                    horizontal_columns=('md', 10, 2),
                    button_map={}) %}
{% endmacro %}

{% if field.flags.required and not required in kwargs %}
    {% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
    {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required)%}
    <div class="form-check">
        <label>
            {{ field()|safe }}
        </label>
    </div>
{% endif %}